### ISSUE TITLE
Deep Learning Libraries Installer for ArcPro 2.9

### ISSUE THREAD

**Issue by grev19** [Esri/deep-learning-frameworks#50]
When extracting ''Deep Learning Libraries Installer for ArcGIS Pro 2.9'' it generates three files  (i.e. the installer file and two zip files). When I try to unzip the file ''ProDeepLearning'' zip file the process is interrupted and the following message appears '' Next volume is required. You need to have the following volume to continue extraction. Insert a disc .........''
I tried several times but the same message appears and the unzipping process is interrupted.
Could you please tell me how to fix this in order to be able to install libraries for Pro 2.9? 
Thank you very much.

**Comment by cleebp** [comment]
You shouldn't need to uncompress the `ProDeepLearning.cab` files to run the setup installer. These are not intended to be unzipped.

Could you try extracting the `ArcGIS_Pro_29_Deep_Learning_Libraries.zip` somewhere on disk, then run the `ProDeepLearning.msi` setup installer and report back what the results are (leaving the `ProDeepLearning.cab` and `ProDeepLearning1.cab` files as is)? Cheers!

**Comment by grev19** [comment]
Thank you very much for your help!
I followed your tips and installed it, but still when I try to run the tool ''Train Deep Learning Model'' in ArcPro
an error appears. (I attach the error in a picture below)
I downloaded the very latest ArcPro version (version 3.0) in an attempt to see whether it works
(however the deep learning libraries that I have installed are destined for Arcpro version 2.9)
Even with the latest ArcPro version, the same errors arise when applying geoprocessing tools related with deep learning.
I guess that the geoprocessing tools in ArcPro environment can't call properly the deep learning libraries and the Python code associated with them, but I don't know how to fix it.
In the past, when I had downloaded ArcPro 2.8 and the corresponding deep learning libraries, the tools worked fine.

Again, thank you very much for your help.

[cid:f5e54814-389d-462c-8704-117bb908ba5f]

**Comment by akendall8969** [comment]
I was having the same issue, after uninstalling the package, seeing the below error, then uninstalling/ reninstalling arcgis Pro 3.0 the error persists:

![DEEP learning Library DL error](https://user-images.githubusercontent.com/108357943/176305543-724fff19-8907-4d64-905b-f7f4d86d57c4.jpg)

I was able to use some of the deep learning tools just the other day, but it just tweaked out. Does this have to do with the update of 2.9 to  3.0? 

Is it where these packages are supposed to be located for proper usage of the libraries? I am so confused and way out of my scope of understanding dependencies, libraries, dll files, etc. Do all of these things need to be centrally located with ArcGIS pro in C:\Programfiles or can they be located somewhere else?

**Comment by cleebp** [comment]
When updating to a newer version of arcgis pro you will first have to uninstall the deep learning libraries via the Add or Remove Programs prompt. Once you install a newer version of Pro you can then install the corresponding deep learning libraries installer from this readme, the deep learning libraries version must match your arcgis pro version or deep learning tools will not work. 

If you have updated to arcgis Pro 3.0 you will need to wait until the deep learning installers are made available for 3.0, this should be happening within the next week or so, the installers usually lag a little behind the latest Pro release. I'll reply when they are available, you'll also see the readme updated.

If you are on arcgis Pro 3.0 and want to use the setup installers you will need to uninstall and downgrade to Pro 2.9 and then install the deep learning libraries from the readme here (the readme also has uninstall instructions) for 2.9.

> @grev19 (however the deep learning libraries that I have installed are destined for Arcpro version 2.9)

You will need a matching arcgis Pro version for the deep learning libraries to work, in this case you will need arcgis Pro 2.9 installed.

> @akendall8969 (s it where these packages are supposed to be located for proper usage of the libraries?)

If you are using the deep learning setup installer provided on the readme here then it will lay down all of the correct deep learning files for you in your "C:/install/path/arcgis/pro/bin/Python" directory on top of the existing installed python files. This is why the deep learning version and pro version must match. Further, when updating Pro the deep learning files will not be touched since they were installed separately and must be manually uninstalled (described above), this is another time when the pro version and deep learning versions can cause problems (if you are on deep learning version 2.8 for instance and install Pro 3.0 nothing will work because the deep learning 2.8 files are still present).

**Comment by jxl090120** [comment]
Deep Learning Libraries 2.9 link downloads 3.0 version. Need 2.9 libraries.

**Comment by scdub** [comment]
@jxl090120 I can confirm, working with the related team to address this.

**Comment by scdub** [comment]
The Pro 2.9 link has been restored, and Pro 3.0 downloads are also now live.
