### ISSUE TITLE
Disconnected deployment of the backbones not found

### ISSUE THREAD

**Issue by dbarretteuk** [Esri/deep-learning-frameworks#55]
I have followed the guidance to deploy the deep learning backbones for a Windows 10 machine running Pro 2.9.x and 3.0  however the tools fail with a urllib error that looks like they are trying to download the backbones as they aren't found. The backbones are all in:

`C:\Users\<username>\.cache\torch\checkpoints` 

however the tool is looking for them in:

`C:\Users\<username>\.cache\torch\hub\checkpoints` 

Manually copying them in to this new folder solves the issue.

**Comment by scdub** [comment]
@dbarretteuk Thanks for your report on this. I've reached out to the team that maintains the backbones and will keep this issue updated with the progress.

**Comment by scdub** [comment]
@dbarretteuk It turns out that the issue is there are different ArcGIS Online versions of the items which are linked to the related Python API and PyTorch releases. I've updated the link in this repositories README to point at the Python API 2.0.1 released backbones which correspond with Pro 3.0 and PyTorch 1.8.2, and use the correct `hub` location by default.

**Comment by dbarretteuk** [comment]
@scdub thats great, thank you for sorting.
