### ISSUE TITLE
 Deep Learning Package Installer Fails with ArcGIS Pro 3.0.3

### ISSUE THREAD

**Issue by sledgesickle** [Esri/deep-learning-frameworks#56]
The installer complains it cannot find ArcGIS Pro 3.0 when trying to install DLP on a clean install of ArcGIS Pro 3.0.3. I gather this might be due to the following:

IMPORTANT: ArcGIS Pro 3.0 does not need to be installed prior to installing ArcGIS Pro 3.0.3. ArcGIS Pro 3.0.3 is cumulative, comprised of 3.0.0, 3.0.1, 3.0.2, and additional updates. ArcGIS Pro 3.0.3 replaces the previous 3.0.x versions and is the new baseline for the 3.0.x patches.

Workaround: If you have a copy of the ArcGIS 3.0 installer (Esri has pulled all 3.0.x versions from their site) you can install ArcGIS 3.0, install the Deep Learning Package, and then upgrade to ArcGIS 3.0.3 from within the application.

**Comment by cinnabon1313** [comment]
I'm having this issue as well, however unfortunately am unable to do a clean install to revert back to ArcGIS Pro 3.0 as my school license only allows me to install the most recent version (3.0.3). Is there another possible work around? :' )

**Comment by scdub** [comment]
@sledgesickle Thank you for your report on this. I'll look into this and get back to this thread.

**Comment by scdub** [comment]
I can confirm this issue. As you found, because 3.0.3 is a full setup and not just a patch, it changes the product code and other registry values for the product the DL installer checks. I've confirmed that temporarily overwriting the HKLM\Software\Esri\ArcGISPro branch with the values from Pro 3.0 allows the installer to work on Pro 3.0.3, and afterward restoring the 3.0.3 registry keys. I'll reach out to the team to see if we can address this in the installers.

**Comment by sroberts86** [comment]
> I can confirm this issue. As you found, because 3.0.3 is a full setup and not just a patch, it changes the product code and other registry values for the product the DL installer checks. I've confirmed that temporarily overwriting the HKLM\Software\Esri\ArcGISPro branch with the values from Pro 3.0 allows the installer to work on Pro 3.0.3, and afterward restoring the 3.0.3 registry keys. I'll reach out to the team to see if we can address this in the installers.

Hi Shaun, how would I go about this temporary fix step by step?

**Comment by sledgesickle** [comment]
@scdub  You're welcome!

**Comment by nicofierrov** [comment]
> The installer complains it cannot find ArcGIS Pro 3.0 when trying to install DLP on a clean install of ArcGIS Pro 3.0.3. I gather this might be due to the following:
> 
> IMPORTANT: ArcGIS Pro 3.0 does not need to be installed prior to installing ArcGIS Pro 3.0.3. ArcGIS Pro 3.0.3 is cumulative, comprised of 3.0.0, 3.0.1, 3.0.2, and additional updates. ArcGIS Pro 3.0.3 replaces the previous 3.0.x versions and is the new baseline for the 3.0.x patches.
> 
> Workaround: If you have a copy of the ArcGIS 3.0 installer (Esri has pulled all 3.0.x versions from their site) you can install ArcGIS 3.0, install the Deep Learning Package, and then upgrade to ArcGIS 3.0.3 from within the application.

ohhh... too late, I can't find ArcGIS 3.0 installer...

**Comment by scdub** [comment]
> > I can confirm this issue. As you found, because 3.0.3 is a full setup and not just a patch, it changes the product code and other registry values for the product the DL installer checks. I've confirmed that temporarily overwriting the HKLM\Software\Esri\ArcGISPro branch with the values from Pro 3.0 allows the installer to work on Pro 3.0.3, and afterward restoring the 3.0.3 registry keys. I'll reach out to the team to see if we can address this in the installers.
> 
> Hi Shaun, how would I go about this temporary fix step by step?

We are working on new setups, and my recommendation is to wait for those, because then you can rely on a fully automated solution without having to make any potentially dangerous or unsupported changes. 

That said, ☠️🐲☠️if you are already comfortable with editing the registry and have backed up the related keys☠️🐲☠️, you can modify the installation `RealVersion` value to `3.0` instead of its current value of `3.0.3` after installing Pro 3.0.3. In a typical per-machine install, the related location would be in `HKEY_LOCAL_MACHINE\SOFTWARE\ESRI\ArcGISPro`. Once the DL installer is run, it should be restored to its original value.

**Comment by sledgesickle** [comment]
@nicofierrov > ohhh... too late, I can't find ArcGIS 3.0 installer...

The ArcGIS Pro 3.0 installer would be in your Documents folder. 

C:\Users\[user]\Documents\ArcGIS Pro 3.0\ArcGISPro\ArcGisPro.msi

**Comment by nicofierrov** [comment]
Thank you @sledgesickle .

I did what @scdub suggested. I changed the 'RealVersion' value in the registry keys, then installed the Deep Learning Package and finally I restored the registry value to the original one. All went OK.

**Comment by sroberts86** [comment]
Yes, thanks. I changed the registry yesterday and it worked. Kind of needed a quick fix for now.

**Comment by scdub** [comment]
Hello @MadelyneA, 

The deep learning installer for 3.0.3 is now live.
