### ISSUE TITLE
Install fails on Azure VM due to cabinet file being downloaded to wrong location

### ISSUE THREAD

**Issue by alexkemp94** [Esri/deep-learning-frameworks#6]
I downloaded the Deep Learning Libraries installer for ArcGIS Pro 2.6 on an Azure VM running Windows 10 Pro and tried to run the installer. The first time I tried I got this error:

![image](https://user-images.githubusercontent.com/33670839/91962133-a658b800-ecfb-11ea-999a-de4d38b2ef28.png)

I then moved the cabinet file from the location it was downloaded to - C:\Users\psadmin\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\TempState\Downloads\ArcGIS_Pro_26_Deep_Learning_Libraries (5).zip - to the location the installer was looking for it (where no cabinet file was previously present) - C:\Users\psadmin\AppData\Local\Temp\Temp1_ArcGIS_Pro_26_Deep_Learning_Libraries (5).zip - and re-ran the installer, **which was successful**.

The image below shows the location the cab file was downloaded to and the location the installer was looking for it.

![image](https://user-images.githubusercontent.com/33670839/91962436-0cddd600-ecfc-11ea-8fbe-a5053a4dc661.png)

Hope this is useful.
Alex

**Comment by scdub** [comment]
@alexkemp94 I've added a blurb under the https://github.com/Esri/deep-learning-frameworks#download section which clarifies the steps necessary to install -- because the .MSI file doesn't know how to reference the .CAB file results when still contained inside of a .zip container, the installer will fail if run directly. Once the archive is extracted, it should work as you mention.
