### ISSUE TITLE
ArcGIS Pro 3.1.0- InvalidArchiveError("Error with archive... [WinError 206] The filename or extension is too long:...

### ISSUE THREAD

**Issue by PerAkeMattias** [Esri/deep-learning-frameworks#66]
With ArcGIS Pro 3.1.0, I have an issue with either cloning the default arcgispro-py3 environment after I used the Deep Learning frameworks installer (which installed successfully) or if I start from scratch with a freshly cloned environment I cannot install the deep learning dependencies using the command "conda install -c esri deep-learning-essentials".  
Either way I get the same error:
InvalidArchiveError("Error with archive C:\\Users\\mw90640\\AppData\\Local\\ESRI\\conda\\pkgs\\tensorflow-base-2.7.0-py39_cuda11.1_cudnn8.1_6.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [WinError 206] The filename or extension is too long: 'C:\\\\Users\\\\mw90640\\\\AppData\\\\Local\\\\ESRI\\\\conda\\\\pkgs\\\\tensorflow-base-2.7.0-py39_cuda11.1_cudnn8.1_6\\\\Lib\\\\site-packages\\\\tensorflow\\\\include\\\\external\\\\cudnn_frontend_archive\\\\_virtual_includes\\\\cudnn_frontend\\\\third_party\\\\cudnn_frontend\\\\include\\\\contrib\\\\nlohmann\\\\json'")

Any idea how to work around this?

**Comment by scdub** [comment]
@PerAkeMattias Thank you for reporting this, this issue is reproducible and other customers have mentioned it. I've added a note and a workaround to the new [known issues](https://github.com/Esri/deep-learning-frameworks/blob/master/README.md#known-issues) section of the README. Let us know if modifying that registry key allows you to create clones successfully, and we will address this in a future build of the installer.

**Comment by PerAkeMattias** [comment]
@scdub That worked for me, thank you!

**Comment by scw** [comment]
This has been addressed with the Pro 3.2 installers. Thanks for the report!
