### ISSUE TITLE
Pro 3.1.4 has different python libraries available between ACCeptance and PRoDuction environments

### ISSUE THREAD

**Issue by johnholistic** [Esri/deep-learning-frameworks#84]
Hi we have two environments that should be very similar and were about to explore the steps as noted in this repository and the blog by Kate Hess to start working with the deep learning modules.  BUt we found one environment has the deep-learning-essentials available for install (our Production where we dont want to test it yet) and 10746 other packages available to install (with 277 installed already) and our ACCeptance environment only has 255 installed and ~8500 packages available and DOES not list the deep learning essentials package.  Any chance you guys know what drives which packages are available besides Pro version?  We do see they channels in the python bin folder seem to both point to here:  https://anaconda.org/esri/repo?page=1 which does list the deep learning essentials, so not sure what is going on, and am guessing you guys may know right off where to check /adjust to make sure our Pro envs are aligned.
Thanks in advance!

**Comment by scw** [comment]
The issue with `deep-learning-essentials` not showing up is a bug that is being addressed and will be patched into Pro in the future, on an affected machine you can run `conda install deep-learning-essentials` and it should install if you'd prefer that to using the installer. For the package counts, there are some existing bugs in the package listing that affects the accuracy of the counts, these should generally be treated as estimates rather than definitive numbers since the dependencies may conflict and we can't full evaluate each package's full dependency set. Additionally, new packages are being added all the time so if one machine was refreshed more recently it would change the count. I'd say that focus on what you want to maintain consistency across the environments, if you're OK with allowing an approximate solve installing `deep-learning-essentials` will work, or either use the installers for 1:1 correspondence, or use `conda env export` to generate a definitive environment and import that on the other machine.

**Comment by scw** [comment]
@johnholistic closing this as I don't think there is anything actionable for the deep learning installers themselves, the core Python team is aware of the listing issue and that is being tracked with this bug: https://support.esri.com/en-us/bug/the-arcgis-pro-python-gui-displays-the-wrong-number-of-bug-000131503

**Comment by johnholistic** [comment]
Thank you for your quick and thorough response, Shaun, we are testing the manual install (and then basic machine learning actions as detailed in this repo) on another environment with the same issue, and if successful will apply to the AVD template and include in the redeploy for ACC and PRD.
