### ISSUE TITLE
Malicious file security warning when installing

### ISSUE THREAD

**Issue by hicksnw** [Esri/deep-learning-frameworks#87]
When I run ProDeepLearning.msi I get a warning from HP Sure Click that this file is malicious. HP Sure Click lists it as Malware name: Binary.Trojan.Generic.

**Comment by scw** [comment]
@hicksnw thanks for your report. I've reviewed both the extracted files and the digitally signed MSI, and checked with some additional sources and we haven't been able to identify any issues with the files. If your machine or administrator has more detailed information, we can look into it, but I believe this is a false positive and would report that to your administrator so they can evaluate it directly. Note that you can also install the files directly without using the installers by [following the developer instructions](https://github.com/Esri/deep-learning-frameworks?tab=readme-ov-file#developer-install-steps) which will download the files directly from conda rather than installing them into the default Pro environment.

**Comment by scw** [comment]
@hicksnw I haven't heard back from you in terms of the malicious check. If you get any details which help identify a specific issue rather than the much more likely false positive, please update this issue, but will close it since we don't have anything actionable to work with currently.
