### ISSUE TITLE
Deep Learning_ Random Forest_ ArcGIS Pro

### ISSUE THREAD

**Issue by hivaos** [Esri/deep-learning-frameworks#92]
I'm working on building a wildfire probability map using Random Forest in ArcGIS Pro 3.3.1. It's my first time doing this, so I would greatly appreciate any assistance. I appreciate any assistance.

**Comment by scw** [comment]
Hi @hivaos, did you have success already in building your model? If you're using Pro, there is a set of tools for forest-based clustering that may be useful to you: https://pro.arcgis.com/en/pro-app/latest/tool-reference/spatial-statistics/forestbasedclassificationregression.htm

From the deep learning side, there are a variety of approaches. If you have specific technical questions I can try to answer them, but you might have better luck asking on https://community.esri.com which has a broad base of users and developers rather than this repo which is mostly dedicated to issues installing and configuring the deep learning package set Pro can function with.
